### ISSUE TITLE
Laravel gereksinimleri

### ISSUE THREAD

**Issue by yahya077** [ismail0234/n11-php-api#20]
Problem 1
    - Root composer.json requires illuminate/support ^7.0, found illuminate/support[v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

bu paket "laravel/framework": "^8.12", içine gönderilmiştir versiyonu yükseltilmesi gerekiyor.

**Comment by ismail0234** [comment]
Sorununu tam olarak anlayamadım? Sorun nedir?

**Comment by yahya077** [comment]
Paketiniz illuminate/support ^7.0 bu paketi kullanıyor ama laravel 8 üstünde bu sürüm kullanılmamaktadır. Bu yüzden paket yüklenmiyor. Sürüm güncellenmesi istiyor.

**Comment by ismail0234** [comment]
@yahya077 Herhangi bir harici paket kullanmıyoruz. Composer dosyasından kontrol edebilirsiniz. https://github.com/ismail0234/n11-php-api/blob/master/composer.json

**Comment by yahya077** [comment]
Şuan framework sürümünü 8.0 a downgrade ettim ve paketi kullanabiliyorum. Teşekkürler.
