### ISSUE TITLE
SaveProduct

### ISSUE THREAD

**Issue by fatihsalman** [ismail0234/n11-php-api#21]
Merhaba saveproduct yaparken aşağıda ki hatayı alıyorum nasıl çözebilirim.

Fatal error: Uncaught IS\PazarYeri\N11\Helper\N11Exception: SOAP-ERROR: Encoding: object has no 'attributes' property in /siteadi.com/vendor/ismail0234/n11-php-api/IS/PazarYeri/N11/Helper/Request.php:87 Stack trace: #0 /siteadi.com/vendor/ismail0234/n11-php-api/IS/PazarYeri/N11/Services/ProductService.php(57): IS\PazarYeri\N11\Helper\Request->sendRequest('SaveProduct', Array) #1 [internal function]: IS\PazarYeri\N11\Services\ProductService->SaveProduct(Object(IS\PazarYeri\N11\Helper\Request), Array) #2 /siteadi.com/vendor/ismail0234/n11-php-api/IS/PazarYeri/N11/Helper/BaseCall.php(65): call_user_func_array(Array, Array) #3 /siteadi.com/admin-paneli/controller/urun-duzenle.php(189): IS\PazarYeri\N11\Helper\BaseCall->__call('SaveProduct', Array) #4 /siteadi.com/app/controller/admin-paneli.php(220): require('/home/fatihler....') #5 /home/fatihler.com/entegrasyon.fatihler.c in /siteadi.com/vendor/ismail0234/n11-php-api/IS/PazarYeri/N11/Helper/Request.php on line 87

**Comment by ismail0234** [comment]
saveproduct fonksiyonunun içerisinde attributes özelliğinin olmadığı yazıyor. Bu fonksiyonu hiç test etme imkanım olmadı. attributes parametresi eklenirse sorun çözülecektir

**Comment by fatihsalman** [comment]
> saveproduct fonksiyonunun içerisinde attributes özelliğinin olmadığı yazıyor. Bu fonksiyonu hiç test etme imkanım olmadı. attributes parametresi eklenirse sorun çözülecektir

ilginiz için teşekkür ederim onu size yazdıktan sonra fark ettim ve ekledim ancak şimdide hiç bir hata döndürmemesine rağmen ürün eklenmiyor. Direkt sizin saveproduct örneğini kullanıyorum.

**Comment by fatihsalman** [comment]
> saveproduct fonksiyonunun içerisinde attributes özelliğinin olmadığı yazıyor. Bu fonksiyonu hiç test etme imkanım olmadı. attributes parametresi eklenirse sorun çözülecektir

hocam size yazdıktan sonra fark ettim onu ekleyebildim ürünü teşekkür ederim ilginiz için şuan sorun yok elinize emeğinize sağlık

**Comment by serhatunur** [comment]
aynı hatayı bende alıyorum sorunu nasıl cözdüğünüzü anlatırmısınız

**Comment by serhatunur** [comment]
$client->product->SaveProduct(
					array(
						'productSellerCode' => 'TF23094823',
						'title' => 'Mavi Toparlayıcı Efekt Skinny Pantolon',
						'subtitle' => 'Curabitur blandit consequat libero, ac suscipit leo luctusrfggfgf',
						'description' => 'Curabitur blandit consequat libero, ac suscipit leo luctus eget. Etiam condimentum augue at quam sagittis bibendum. Quisque vitae malesuada urna. Proi',
						'domestic' => 'false',
						'category' => array(
							'id' => '1002201'
						),
						'specialProductInfoList' => array(
							'specialProductInfo' => array(
								'key' => '?',
								'value' => '?',
							)
						),
						'price' => '185.00',
						'currencyType' => '1',
						'images' => array(
							'image' => array(
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '1',
								),
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '2',
								),
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '3',
								),
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '4',
								),
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '5',
								),
								array(
									'url' => 'https://contents.mediadecathlon.com/p1058366/k20d731c11ef86aad6039daa20fb66dc3/1058366_default.jpg',
									'order' => '6',
								)
							)
						),
						'approvalStatus' => '1',
						'attribute' => array(),
						'saleStartDate' => '',
						'saleEndDate' => '',
						'productionDate' => '',
						'expirationDate' => '',
						'productCondition' => 1,
						'preparingDay' => 3,
						'discount' => array(
							'startDate' => '',
							'endDate' => '',
							'type' => '',
							'value' => '',
						),
						'shipmentTemplate' => 'termos',
						'stockItems' => array(
							'stockItem' => array(
								array(
									'bundle' => 'false',
									'mpn' => '112',
									'gtin' => '0190198066473',
									'oem' => '',
									'quantity' => '855',
									'n11CatalogId' => '',
									'sellerStockCode' => '112',
									'optionPrice' => '185.00',
									'attributes' => array(
										'attribute' => array(
											array(
												'name' => 'Sezon',
												'value' => '2013 Sonbahar-Kış'
											),
											array(
												'name' => 'Cinsiyet',
												'value' => 'Erkek',
											),
											array(
												'name' => 'Beden',
												'value' => '145',
											),
											array(
												'name' => 'Desen',
												'value' => 'Nakışlı',
											),
											array(
												'name' => 'Ürün_Detayı',
												'value' => 'Kapüşonlu',
											),
											array(
												'name' => 'İçerik',
												'value' => 'Brode,Brokar,İnterlok',
											),
											array(
												'name' => 'Marka',
												'value' => 'Esteem',
											),
											array(
												'name' => 'Renk',
												'value' => 'Gri',
											)
										)
									)
								)
							)
						),
						'unitInfo' => array(
							'unitType' => '',
							'unitWeight' => ''
						),
						'maxPurchaseQuantity' => '122',
						'groupAttribute' => '',
						'groupItemCode' => '',
						'itemName' => ''
					)
				);
Bu fonksiyon unun içerisinde attributes parametresi ekli başka bir yere mi eklememiz lazım  sorunu anlayamadım yardımcı olur musunuz

**Comment by serhatunur** [comment]
teşekkürler sorunu çözdüm
