### ISSUE TITLE
api dil kodlaması

### ISSUE THREAD

**Issue by bllbgc** [ismail0234/n11-php-api#22]
hocam ben kendi yaptığım apiyi kullanıyorum. ama bir sorunum var sürekli başıma bela oluyor. çözemiyorum. fikir almak istedim. sorunum şu. n11 üzerinden herhangi bir sorgulama yaparken bir anda sorgulama yapmayı kesiyor. hata veriyor. apinin başına setlocale ile türkçe dil kodu ekliyorum düzeliyor.  ertesi gün yine sorgulama yapmıyor. bu kez eklediğim satırı siliyorum düzeliyor. fikir almak istedim. cevaplarsan memnun olurum.

**Comment by ismail0234** [comment]
Tuhaf daha önce hiç böyle sorunla karşılamadım. İlginç bir sorun gibi duruyor
