### ISSUE TITLE
N11Client not found

### ISSUE THREAD

**Issue by mioversolna** [ismail0234/n11-php-api#23]

**Comment by keremkutlu1234** [comment]
Visual Studio Code'da klasör olarak açınca 2. resimdeki N11Client() fonksiyonunun altı çizli olmuyor yani 2. fotoyu klasör açmadan aldığım için altı çizili görünüyor.

**Comment by ismail0234** [comment]
@keremkutlu1234 eklemiş olduğun 2. resmi kaldırdım. Api key ve şifreni bu tarz herkese açık platformlarda paylaşmamanı tavsiye ederim. Composer ile doğru kurulum gerçekleştirdiniz mi?

**Comment by keremkutlu1234** [comment]
aaah kusura bakmayın onu unuttum :/

evet composer ile doğru kurulum yaptım örnek olarak tam kurulumu yapılmış klasör verebilirseniz daha iyi olur çünkü ben gerçekten hiç bir şey anlamadım daha doğrusu pek composer kullanmıyorum yanlış kurulum yapmış olabilirim

**Comment by keremkutlu1234** [comment]
Yani örnek klasör olmasada olur gerçi sorunu anlayalım yeter
