### ISSUE TITLE
SOAP Oturumu Başarısız

### ISSUE THREAD

**Issue by mrtsglk** [ismail0234/n11-php-api#24]
Aynı sorguyu tekrarladığımda SOAP Oturumu başarısız hatası alıyorum bu sorunu nasıl çözebilirim.

**Comment by ismail0234** [comment]
Sunucunuzda SOAP'ın kurulu olup olmadığını kontrol edebilirsiniz.

**Comment by mrtsglk** [comment]
Soap kurulu sorunu şöyle anlatayım biraz eksik bilgi verdim. Şimdi sayfada satışları getiriyorum. Normalde her hangi bir sıkıntı olmuyor satışlar listeleniyor. Fakat sayfayı yenilediğimde bu hatayı alıyorum. Tekrar yenileyince gene siparişler gözüküyor. Böyle 2 3 kez yenilemede bir hata veriyor.

**Comment by ismail0234** [comment]
Belki api ratelimit'e takılıyor olabilir misiniz?

**Comment by mrtsglk** [comment]
Sorunu şu şekilde çözdüm.

`$this->client = new \SoapClient($this->serviceUrl, array("trace" => 1, "exception" => false, 'cache_wsdl' => WSDL_CACHE_NONE));`

connectSoap fonksiyonunu aşağıdaki şekilde değiştirdim.

`$this->client = new \SoapClient($this->serviceUrl, array("trace" => 1, "exception" => false,'connection_timeout' => 500000, 'cache_wsdl' => WSDL_CACHE_BOTH, 'keep_alive' => false));`
