### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by ozgurkaracam** [ismail0234/n11-php-api#27]
merhaba hocam, webhook'un cronjob ile neden kullanılmaması gerektiğini söyler misiniz. teşekkürler

**Comment by ismail0234** [comment]
> merhaba hocam, webhook'un cronjob ile neden kullanılmaması gerektiğini söyler misiniz. teşekkürler

Webhook sonsuz döngü içerisinde çalışmaktadır. Cronjob ile çalıştırırsanız, her çalışmasında daha fazla sonsuz döngü çalışacağından sunucuyu kullanılamaz hale getirirsiniz.
