### ISSUE TITLE
Merhaba Ürün yüklemeyi denerken SOAP-ERROR: Encoding: object has no 'images' property hatası alıyorum. 

### ISSUE THREAD

**Issue by scngnr** [ismail0234/n11-php-api#31]
$client->product->SaveProduct(
    array(
      'productSellerCode' => "test",
      'title' => "test1",
      'subtitle' => "test1",
      'description' => "11",
      'attributes' => array(
        'attribute' => array(

        )
      ),
      'category' => array(
        'id' => "11"
      ),
      'price' => 34,
      'currencyType' => '1',
      'images' => [
        'image' => [
          array(
          'url' => 'http://www.ewsyonetim.com/product-images-resized/2419_1.jpg',
          'order' => '1',
          )
          ]
        ],
      'saleStartDate' => '',
      'saleEndDate' => '',
      'productionDate' => '',
      'expirationDate' => '',
      'productCondition' => 1,
      'preparingDay' => 2,
      'discount' => array(
        'startDate' => '',
        'endDate' => '',
        'type' => '',
        'value' => '',
      ),
      'shipmentTemplate' => "Ews",
      'stockItems' => array(
        'stockItem' => array(
          'attributes' => array(
            'attribute' => array(
              'name' => '',
              'value' => '',
            )
          ),
            'bundle' => 'false',
            'mpn' => "1",
            'gtin' => "1",
            'oem' => '',
            'quantity' => "1",
            'n11CatalogId' => '',
            'sellerStockCode' => 'test',
            'optionPrice' => "",
          )
        ),
      'domestic' => 'false',
      'specialProductInfoList' => array(
        'specialProductInfo' => array(
          'key' => '?',
          'value' => '?',
        )
      ),
      'approvalStatus' => '1',
      'groupAttribute' => '',
      'groupItemCode' => '',
      'itemName' => '',
      'unitInfo' => '',
      'maxPurchaseQuantity' => "111",
      )
  ));

**Comment by ufukseyithan** [comment]
Bu sorunu çözebildiniz mi?

**Comment by scngnr** [comment]
Çözdüm,
İlginiz için teşekkür ederim.

12 Haz 2023 Pzt 16:01 tarihinde Ufuk Seyithan Erdem <
***@***.***> şunu yazdı:

**Comment by ufukseyithan** [comment]
Nasıl çözdüğünüzü öğrenebilir miyim? Aynı hatayla ben de karşılaşıyorum.

**Comment by scngnr** [comment]
N11e iletilen Array içerisinde Optionprice
Sonrasına
images.image.url,
images.image.order
Ekleyerek çözmüştüm.

3-4 aydır geliştirmeyi bıraktım. Farklı birşey eklenmediyse bu şekilde

12 Haz 2023 Pzt 16:07 tarihinde Ufuk Seyithan Erdem <
***@***.***> şunu yazdı:

**Comment by ufukseyithan** [comment]
Teşekkür ederim. Anlaşılan her bir _stockItem_ için _images_ alanı belirlenmesi gerekiyor. Yalnız gelin görün ki N11'in kendi dökümantasyonunda bu bilgi eksik.

**Comment by scngnr** [comment]
Karşılaştığınız hatayı xml formatında olmak şartıyla paylaşırsanız doğrudan
n11 geliştiricilerinden de yardım alabilirsiniz bilginiz olsun.

12 Haz 2023 Pzt 16:22 tarihinde Ufuk Seyithan Erdem <
***@***.***> şunu yazdı:
